@startuml
<style>
    title {
      HorizontalAlignment center
      FontSize 18
      padding 20
    }
</style>

title Use Case - Configure the Location of the House \nProcess View Level 3 - Backend Interaction \n Main Success Scenario
autonumber

!pragma teoz true

box "<<container (C4)>>\n     :Backend" #LightGrey
  participant "**<<component (C4)>>**\n:Server" as SERVER
  participant "**<<component (C4)>>**\n:Database" as DB
end box

[o-> SERVER : PATCH /house (location information)
activate SERVER

SERVER -> DB: Get persisted house
activate DB
DB --> SERVER: Retrieve house
deactivate DB
|||
SERVER -> SERVER : Update house location
|||
SERVER -> DB : Save updated house
activate DB
DB --> SERVER : Send validation
deactivate DB

[o<-- SERVER : new house data + HTTP Status
deactivate SERVER

@enduml