@startuml
<style>
    title {
      HorizontalAlignment center
      FontSize 18
      padding 20
    }
</style>

title Use Case - List Existing Devices in a Room \nProcess View Level 3 \
- Backend Interaction \n Main Success Scenario
autonumber

!pragma teoz true

box "<<container (C4)>>\n     :Backend" #LightGrey
  participant "**<<component (C4)>>**\n:Server" as SERVER
  participant "**<<component (C4)>>**\n:Database" as DB
end box

[o-> SERVER : GET /devices (room information)
activate SERVER

SERVER -> DB: Verify if room exists
activate DB
DB --> SERVER: Send validation
deactivate DB
|||
SERVER -> DB: Request all devices in the room
activate DB
DB --> SERVER: Retrieve devices
deactivate DB

[o<-- SERVER : devices data + HTTP Status
deactivate SERVER

@enduml