@startuml

title Use Case - Get Maximum Temperature Difference Between an Outdoor \nand Indoor Device in a Given Period \nProcess View Level 2\nSuccess Scenario
autonumber

!pragma teoz true
box "  <<System>>\n:SmartHome" #DarkGrey


participant "**<<container (C4)>>**\n:Backend" as BE

[o-> BE: GET /logs (devices and time information)
activate BE

note right
**This feature is not available in the Web App.**
end note
[o<-- BE : request result + HTTP Status
deactivate BE

end box

@enduml
