@startuml
'https://plantuml.com/class-diagram

title Implementation View - Level 2

package System{
package BackEnd as B{
}
'package FrontEnd as F{
'}
'package WeatherService as W{
'}
}

'F..>B
'F..>W
'B..>W

@enduml